[package]
name = "kernel"
version = "0.0.1"
edition = "2021"
authors = ["TJ Patel, Brian Almeida"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


